---
abstract: 'BeLike::BINGOS when you build your dists'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-BINGOS
requires:
  Dist::Zilla: 4.200006
  Dist::Zilla::Plugin::Clean: 0.02
  Dist::Zilla::Plugin::CompileTests: 1.110930
  Dist::Zilla::Plugin::GithubMeta: 0.10
  Dist::Zilla::Plugin::MetaJSON: 4.200006
  Dist::Zilla::Plugin::PkgVersion: 4.200006
  Dist::Zilla::Plugin::PodCoverageTests: 4.200006
  Dist::Zilla::Plugin::PodSyntaxTests: 4.200006
  Dist::Zilla::Plugin::PodWeaver: 3.101641
  Dist::Zilla::Plugin::ReadmeFromPod: 0.14
  Moose: 1.08
  perl: 5.008005
resources:
  homepage: http://github.com/bingos/dist-zilla-pluginbundle-bingos/tree
  repository: git://github.com/bingos/dist-zilla-pluginbundle-bingos.git
version: 0.10
